apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq1
  name: rabbitmq1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq1
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: RABBITMQ_DEFAULT_PASS
          value: Password
        - name: RABBITMQ_DEFAULT_USER
          value: Administrator
        image: rabbitmq:3-management-alpine
        name: rabbitmq1
        ports:
        - containerPort: 5672
      hostname: rabbitmq1

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq1
spec:
  type: ClusterIP
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq1
